version: '3'
services:
  web:
    image: nginx:alpine
    volumes:
      - ./webapp/public:/var/www/html
    ports:
      - 8080:80

  database:
    image: mysql:5.7
    volumes:
      - ./initdb.d/:/docker-entrypoint-initdb.d/:ro
    environment:
      TZ: Asia/Tokyo
      MYSQL_DATABASE: isubata
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  redis:
    image: redis:alpine
